#!/usr/bin/env python3
"""Generate the embedding-space diagnostics LaTeX tables from the benchmark.

Reads the per-TC / per-variant checkpoints under ``output/synthetic_benchmark``
(epoch-0 and epoch-5 embeddings, keyed by ``keys.json``) together with the
held-out test labels, and writes two LaTeX tables to ``latex/assets/visuals/``:

* ``diagnostics_summary.tex``          -- the three showcase test cases
                                          (tc07, tc09, tc14) x all seven variants.
* ``diagnostics_summary_appendix.tex`` -- the remaining twelve test cases x all
                                          seven variants, as a ``longtable``.

Per (tc, variant) the columns are: held-out accuracy at initialization
(epoch 0) and after five fine-tuning epochs, the number of distinct
initialization vectors among the test entities, the silhouette score of the
label clustering at epoch 0, and the mean cosine between the epoch-0 and
epoch-5 vectors.

Run from the repo root:  uv run python scripts/plot/diagnostics_table.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
from sklearn.metrics import silhouette_score

from _common import REPO_ROOT, SCRIPTS_DIR  # noqa: E402

if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from _evaluate import load_labeled_txt  # noqa: E402

BENCH_ROOT = REPO_ROOT / "output" / "synthetic_benchmark"
DEFAULT_OUT = REPO_ROOT / "latex" / "assets" / "visuals"

SHOWCASE_TCS = ("tc07", "tc09", "tc14")
ALL_TCS = tuple(f"tc{n:02d}" for n in range(1, 16))
REST_TCS = tuple(tc for tc in ALL_TCS if tc not in SHOWCASE_TCS)

# vanilla baseline, then the classic (high-LR) recipe, then the concept-bound
# (protected-LR) recipe; matches the narrative in the results chapter.
VARIANTS = (
    "vanilla",
    "p1_classic",
    "p2_classic",
    "p3_classic",
    "p1_bound",
    "p2_bound",
    "p3_bound",
)

INIT_CKPT = "ckpt_epoch00.npz"
FINAL_CKPT = "ckpt_epoch05.npz"


def test_labels(tc: str) -> tuple[list[str], np.ndarray]:
    path = (
        REPO_ROOT
        / "v1"
        / "synthetic_ontology"
        / tc
        / "synthetic_ontology"
        / "1000"
        / "train_test"
        / "test.txt"
    )
    return load_labeled_txt(path)


def compute_row(tc: str, variant: str) -> dict:
    run_dir = BENCH_ROOT / tc / variant
    tokens, y = test_labels(tc)

    # A handful of test entities (tc01/02/03/05) never appear in any walk and so
    # have no embedding; restrict the geometric metrics to the embedded entities.
    index = {k: i for i, k in enumerate(json.loads((run_dir / "keys.json").read_text("utf-8")))}
    rows = [index[t] for t in tokens if t in index]
    y = y[[t in index for t in tokens]]

    x0 = np.load(run_dir / INIT_CKPT)["vectors"][rows]
    x5 = np.load(run_dir / FINAL_CKPT)["vectors"][rows]
    accs = json.loads((run_dir / "metrics.json").read_text("utf-8"))["accs"]

    n_distinct = len({row.tobytes() for row in np.round(x0, 6)})
    sil = float(silhouette_score(x0, y))
    cos = float(
        np.mean(
            np.sum(x0 * x5, axis=1)
            / (np.linalg.norm(x0, axis=1) * np.linalg.norm(x5, axis=1) + 1e-12)
        )
    )
    return dict(
        acc_init=float(accs[0]),
        acc_final=float(accs[-1]),
        n_distinct=n_distinct,
        n_total=int(len(y)),
        silhouette=sil,
        cos=cos,
    )


def body_rows(tcs: tuple[str, ...]) -> list[str]:
    lines: list[str] = []
    for ti, tc in enumerate(tcs):
        for k, variant in enumerate(VARIANTS):
            r = compute_row(tc, variant)
            tc_cell = tc if k == 0 else ""
            variant_cell = variant.replace("_", "\\_")
            lines.append(
                f"{tc_cell} & \\texttt{{{variant_cell}}}"
                f" & {r['acc_init']:.3f} & {r['acc_final']:.3f}"
                f" & {r['n_distinct']} / {r['n_total']}"
                f" & {r['silhouette']:.3f} & {r['cos']:.3f} \\\\"
            )
        if ti != len(tcs) - 1:
            lines.append("\\midrule")
    return lines


HEADER = (
    "\\textbf{TC} & \\textbf{variant} & \\textbf{acc@init} & \\textbf{acc@final}"
    " & \\textbf{distinct init} & \\textbf{silhouette} & \\textbf{cos(e0,\\,e5)} \\\\"
)
BANNER = "% Auto-generated by scripts/plot/diagnostics_table.py — do not edit by hand."


def write_main_table(out: Path) -> None:
    lines = [
        BANNER,
        "\\begin{tabular}{llccccc}",
        "\\toprule",
        HEADER,
        "\\midrule",
        *body_rows(SHOWCASE_TCS),
        "\\bottomrule",
        "\\end{tabular}",
    ]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


def write_appendix_table(out: Path) -> None:
    lines = [
        BANNER,
        "\\begin{longtable}{llccccc}",
        "\\caption{Embedding-space diagnostics at initialization (epoch 0) for the"
        " remaining twelve synthetic test cases (all but the showcase tc07, tc09 and"
        " tc14), across all seven variants. Columns match"
        " Table~\\ref{tab:diag_summary}.}",
        "\\label{tab:diag_summary_appendix} \\\\",
        "\\toprule",
        HEADER,
        "\\midrule",
        "\\endfirsthead",
        "\\toprule",
        HEADER,
        "\\midrule",
        "\\endhead",
        "\\midrule",
        "\\multicolumn{7}{r}{\\footnotesize continued on next page} \\\\",
        "\\endfoot",
        "\\bottomrule",
        "\\endlastfoot",
        *body_rows(REST_TCS),
        "\\end{longtable}",
    ]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    write_main_table(out_dir / "diagnostics_summary.tex")
    write_appendix_table(out_dir / "diagnostics_summary_appendix.tex")


if __name__ == "__main__":
    main()
