"""
Figures and LaTeX table for the reduced fine-tuning walk budget experiment.

Inputs:
  method_proposal/data/<tc>.json          - full budget (100 walks/entity)
  method_proposal/data/nw50/<tc>.json     - reduced budget (50)
  method_proposal/data/nw25/<tc>.json     - reduced budget (25)

Outputs:
  latex/assets/nw50/<tc>_nw50.png         - Section 3.6: vanilla@100 vs
                                            vanilla/p1_classic/p2_classic@50
  latex/assets/nw_bound/<tc>_nwbound.png  - Ch.5 revisit: vanilla@100 vs
                                            p{1,2,3}_bound@50 (solid) / @25 (dashed)
  latex/assets/reduced_walks_table.tex    - mean final accuracy per budget
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = next(p for p in Path(__file__).resolve().parents if (p / "pyproject.toml").is_file())
DATA = ROOT / "method_proposal" / "data"
ASSETS = ROOT / "latex" / "assets"

COLORS = {
    "vanilla": "#9e9e9e",
    "p1_classic": "#c5b3e6",
    "p2_classic": "#9575cd",
    "p1_bound": "#90caf9",
    "p2_bound": "#1e88e5",
    "p3_bound": "#0d47a1",
}

TCS = sorted(p.stem for p in (DATA / "nw50").glob("tc*.json") if p.stem != "tc16")
FOCUS = [f"tc{i:02d}" for i in range(7, 13)]


def load(tc: str, budget: int | None) -> dict[str, dict]:
    path = DATA / f"{tc}.json" if budget is None else DATA / f"nw{budget}" / f"{tc}.json"
    return {r["variant"]: r for r in json.loads(path.read_text())}


def plot_classic(tc: str) -> None:
    full, nw50 = load(tc, None), load(tc, 50)
    fig, ax = plt.subplots(figsize=(4.2, 3.0))
    series = [
        (full["vanilla"], COLORS["vanilla"], "-", "vanilla (100 walks)"),
        (nw50["vanilla"], COLORS["vanilla"], "--", "vanilla (50 walks)"),
        (nw50["p1_classic"], COLORS["p1_classic"], "-", "p1_classic (50 walks)"),
        (nw50["p2_classic"], COLORS["p2_classic"], "-", "p2_classic (50 walks)"),
    ]
    for r, color, ls, label in series:
        ax.plot(range(len(r["accs"])), r["accs"], marker="o", ms=3,
                color=color, ls=ls, label=label)
    ax.set_ylim(0.4, 1.02)
    ax.axhline(0.5, color="k", lw=0.5, ls=":")
    ax.grid(alpha=0.3)
    ax.set_xlabel("epoch (0 = initialization)")
    ax.set_ylabel("test accuracy")
    ax.legend(fontsize=6.5, loc="lower right")
    fig.tight_layout()
    out = ASSETS / "nw50" / f"{tc}_nw50.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=150)
    plt.close(fig)


def plot_bound(tc: str) -> None:
    full, nw50, nw25 = load(tc, None), load(tc, 50), load(tc, 25)
    fig, ax = plt.subplots(figsize=(4.2, 3.0))
    ax.plot(range(len(full["vanilla"]["accs"])), full["vanilla"]["accs"],
            marker="o", ms=3, color=COLORS["vanilla"], label="vanilla (100 walks)")
    for v in ("p1_bound", "p2_bound", "p3_bound"):
        ax.plot(range(len(nw50[v]["accs"])), nw50[v]["accs"], marker="o", ms=3,
                color=COLORS[v], label=f"{v} (50 walks)")
        ax.plot(range(len(nw25[v]["accs"])), nw25[v]["accs"], marker="o", ms=2,
                color=COLORS[v], ls="--", lw=1.0)
    ax.plot([], [], color="k", ls="--", lw=1.0, label="(dashed: 25 walks)")
    ax.set_ylim(0.4, 1.02)
    ax.axhline(0.5, color="k", lw=0.5, ls=":")
    ax.grid(alpha=0.3)
    ax.set_xlabel("epoch (0 = initialization)")
    ax.set_ylabel("test accuracy")
    ax.legend(fontsize=6.5, loc="lower right")
    fig.tight_layout()
    out = ASSETS / "nw_bound" / f"{tc}_nwbound.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=150)
    plt.close(fig)


def mean_final(rows_by_tc: dict[str, dict], variant: str, tcs: list[str]) -> float:
    return sum(rows_by_tc[tc][variant]["final_acc"] for tc in tcs) / len(tcs)


def summary_table() -> None:
    full = {tc: load(tc, None) for tc in TCS}
    nw50 = {tc: load(tc, 50) for tc in TCS}
    nw25 = {tc: load(tc, 25) for tc in TCS}
    variants = ["vanilla", "p1_classic", "p2_classic", "p3_classic",
                "p1_bound", "p2_bound", "p3_bound"]

    def row(variant: str) -> str:
        cells = [f"{mean_final(data, variant, TCS):.3f}" for data in (full, nw50, nw25)]
        name = variant.replace("_", "\\_")
        return f"\\texttt{{{name}}} & " + " & ".join(cells) + " \\\\"

    lines = [
        "% Auto-generated by scripts/plot_reduced_walks.py",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "\\textbf{Variant} & 100 walks (full) & 50 walks & 25 walks \\\\",
        "\\midrule",
        *[row(v) for v in variants],
        "\\bottomrule",
        "\\end{tabular}",
    ]
    out = ASSETS / "reduced_walks_table.tex"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")

    # console summary for the thesis text
    for label, data in (("100", full), ("50", nw50), ("25", nw25)):
        print(f"-- budget {label}")
        for v in variants:
            print(f"   {v:>11}  focus={mean_final(data, v, FOCUS):.3f}  all={mean_final(data, v, TCS):.3f}")


if __name__ == "__main__":
    print(f"TCs: {TCS}")
    for tc in TCS:
        plot_classic(tc)
        plot_bound(tc)
        print(f"{tc} done", flush=True)
    summary_table()
