"""Generate the per-TC fine-tuning runtime table (latex/assets/runtime_per_tc_table.tex).

Three stages reported separately plus a Total column, in pipeline order:
  1. pretraining           pretrain_sgns + normalize_codes
  2. init (w/ pretrain)    init_vectors + concept_bound
  3. finetuning            finetune_sgns
  4. total                 sum of the three

The protograph-creation stage is negligible (~0.02-0.04 s) and is excluded.

Vanilla (from-scratch RDF2Vec) has no pretraining and a random init, so only
finetuning applies; the other stages are shown as "--".

The table is emitted as a ``longtable`` (caption + label included) so it can
break across pages; it is meant to be ``\\input`` directly (not inside a float).

Layout: TC rows (tc01-tc12), variant sub-rows each (\\multirow).
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = next(p for p in Path(__file__).resolve().parents if (p / "pyproject.toml").is_file())
RESULTS_JSON = ROOT / "output" / "synthetic_benchmark" / "summary.json"
OUT_TEX = ROOT / "latex" / "assets" / "runtime_per_tc_table.tex"

TCS = [f"tc{i:02d}" for i in range(1, 13)]  # tc01..tc12
# (variant, proto_kind|None); None == vanilla baseline
VARIANTS = [
    ("vanilla", None),
    ("p1_classic", "p1"), ("p2_classic", "p2"), ("p3_classic", "p3"),
    ("p1_bound", "p1"), ("p2_bound", "p2"), ("p3_bound", "p3"),
]
DASH = "--"
# TCs shown as rows but excluded from the mean (runtime outliers whose much
# larger walk corpora would dominate the average): tc04 is ~15x the others.
MEAN_EXCLUDE = {"tc04"}


def stage_values(row: dict, variant: str, kind: str | None):
    """Return (pretrain, init, finetune) with None for inapplicable stages."""
    if kind is None:  # vanilla: no pretraining, random init -> only fine-tuning
        return None, None, row["finetune_s"]
    return row["pretrain_s"], row["init_s"], row["finetune_s"]


def fmt(x) -> str:
    return DASH if x is None else f"{x:.2f}"


def total(vals) -> float:
    return sum(v for v in vals if v is not None)


def vlabel(variant: str) -> str:
    return "\\texttt{" + variant.replace("_", "\\_") + "}"


def main() -> None:
    raw = json.loads(RESULTS_JSON.read_text(encoding="utf-8"))
    # output/synthetic_benchmark/summary.json is a flat list of per-(tc, variant)
    # records; index it for lookup.
    index = {(r["tc"], r["variant"]): r for r in raw}
    present = {tc for tc, _ in index}
    tcs = [tc for tc in TCS if tc in present]
    nvar = len(VARIANTS)

    # Column headers, reused for the first page and every continuation page.
    header = [
        " & & & \\textbf{Init} & \\textbf{Fine-} & \\\\",
        "\\textbf{TC} & \\textbf{Variant} & \\textbf{Pretrain} & "
        "\\textbf{(w/ pretrain)} & \\textbf{tuning} & \\textbf{Total} \\\\",
        "\\midrule",
    ]

    lines = [
        "% Auto-generated by scripts/plot_runtime_per_tc.py",
        "\\begin{longtable}{llcccc}",
        "\\caption{Per-test-case runtime (seconds), broken into three pipeline "
        "stages plus an end-to-end total. Pretraining depends only on the "
        "protograph kind (P1/P2/P3) and is shared by the \\texttt{classic} and "
        "\\texttt{bound} variants; the init column includes the concept-bound "
        "construction for the \\texttt{*\\_bound} variants. The \\texttt{vanilla} "
        "baseline trains from scratch with a random init (only fine-tuning "
        "applies). Walk generation and the negligible protograph-creation stage "
        "($\\approx$0.02--0.04\\,s) are excluded. The final block reports the "
        "per-variant mean, excluding tc04 whose much larger walk corpus "
        "($\\approx$15$\\times$) makes its runtime a far outlier. All RDF2Vec "
        "stages were run with 16 worker threads, so the absolute seconds scale "
        "with the thread count."
        "}\\label{tab:runtime_per_tc}\\\\",
        "\\toprule",
        *header,
        "\\endfirsthead",
        "\\multicolumn{6}{c}{\\tablename\\ \\thetable\\ -- continued from "
        "previous page}\\\\",
        "\\toprule",
        *header,
        "\\endhead",
        "\\midrule",
        "\\multicolumn{6}{r}{\\textit{continued on next page}}\\\\",
        "\\endfoot",
        "\\bottomrule",
        "\\endlastfoot",
    ]

    # \\* keeps each TC's variant block from breaking across a page so the
    # \multirow label stays aligned with its rows.
    sums = {v: [0.0, 0.0, 0.0] for v, _ in VARIANTS}
    for ti, tc in enumerate(tcs):
        in_mean = tc not in MEAN_EXCLUDE
        for vi, (variant, kind) in enumerate(VARIANTS):
            vals = stage_values(index[(tc, variant)], variant, kind)
            if in_mean:
                for j in range(3):
                    sums[variant][j] += vals[j] or 0.0
            head = f"\\multirow{{{nvar}}}{{*}}{{{tc}}}" if vi == 0 else ""
            cells = " & ".join(fmt(x) for x in vals)
            eol = "\\\\" if vi == nvar - 1 else "\\\\*"
            lines.append(f"{head} & {vlabel(variant)} & {cells} & {fmt(total(vals))} {eol}")
        if ti != len(tcs) - 1:
            lines.append("\\midrule")

    n = sum(1 for tc in tcs if tc not in MEAN_EXCLUDE)
    lines.append("\\midrule")
    for vi, (variant, kind) in enumerate(VARIANTS):
        mean = [sums[variant][j] / n for j in range(3)]
        if kind is None:  # keep dashes for vanilla's inapplicable stages
            mean = [None, None, mean[2]]
        head = f"\\multirow{{{nvar}}}{{*}}{{mean}}" if vi == 0 else ""
        cells = " & ".join(fmt(x) for x in mean)
        eol = "\\\\" if vi == nvar - 1 else "\\\\*"
        lines.append(f"{head} & {vlabel(variant)} & {cells} & {fmt(total(mean))} {eol}")

    lines += ["\\end{longtable}", ""]
    OUT_TEX.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_TEX} ({len(tcs)} TCs shown, {n} in mean, {nvar} variants)")


if __name__ == "__main__":
    main()
